src/Entity/House.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HouseRepository")
 */
class House
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\City", inversedBy="id")
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $remodelationYear;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $main_description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $secondary_description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $main_image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $constructionYear;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="float")
     */
    private $netArea;

    /**
     * @ORM\Column(type="float")
     */
    private $grossArea;

    /**
     * @ORM\Column(type="boolean")
     */
    private $rent;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\HouseImage", mappedBy="house", orphanRemoval=true)
     */
    private $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        $this->slug = preg_replace("/[\s_]/", "-", preg_replace("/[\s-]+/", " ",
            preg_replace("/[^a-z0-9_\s-]/", "", strtolower($this->name))));

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getRemodelationYear(): ?\DateTimeInterface
    {
        return $this->remodelationYear;
    }

    public function setRemodelationYear(\DateTimeInterface $remodelationYear): self
    {
        $this->remodelationYear = $remodelationYear;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getLocation(): ?string {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getMainDescription(): ?string {
        return $this->main_description;
    }

    public function setMainDescription(string $main_description): self
    {
        $this->main_description = $main_description;

        return $this;
    }

    public function getSecondaryDescription(): ?string {
        return $this->secondary_description;
    }

    public function setSecondaryDescription(string $secondary_description): self
    {
        $this->secondary_description = $secondary_description;

        return $this;
    }

    public function getMainImage(): ?string {
        return $this->main_image;
    }

    public function setMainImage(string $main_image): self
    {
        $this->main_image = $main_image;

        return $this;
    }

    public function getConstructionYear(): ?\DateTimeInterface
    {
        return $this->constructionYear;
    }

    public function setConstructionYear(\DateTimeInterface $constructionYear): self
    {
        $this->constructionYear = $constructionYear;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getNetArea(): ?float
    {
        return $this->netArea;
    }

    public function setNetArea(float $netArea): self
    {
        $this->netArea = $netArea;

        return $this;
    }

    public function getGrossArea(): ?float
    {
        return $this->grossArea;
    }

    public function setGrossArea(float $grossArea): self
    {
        $this->grossArea = $grossArea;

        return $this;
    }

    public function getRent(): ?bool
    {
        return $this->rent;
    }

    public function setRent(bool $rent): self
    {
        $this->rent = $rent;

        return $this;
    }

    /**
     * @return Collection|HouseImage[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(HouseImage $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setHouse($this);
        }

        return $this;
    }

    public function removeImage(HouseImage $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getHouse() === $this) {
                $image->setHouse(null);
            }
        }

        return $this;
    }

}

src/Controller/HouseController.php
<?php

namespace App\Controller;

use App\Entity\House;
use App\Entity\City;
use App\Entity\HouseImage;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HouseController extends AbstractController
{
    /**
     * @Route("/{type}/cidades/{slug}/{housename}", name="house")
     */
    public function index($type, $slug, $housename)
    {
        switch ($type){
            case "apartamentos":
                $rent = 1;
                $typeName= "Apartamentos";
                $typeSearch = "imoveis";
                break;
            case "imoveis":
                $rent = 0;
                $typeName = "Imóveis";
                $typeSearch = "apartamentos";
                break;
            default:
                $rent = 1;
        }
        $house = $this->findHouse($rent, $slug, $housename);
        $images = $this->getDoctrine()->getRepository(HouseImage::class)->findBy(array("house"=>$house->getId()));
        return $this->render('house/index.html.twig', [
            'controller_name' => 'HouseController',
            'house' => $house,
            'city' => $slug,
            'type' => $typeName,
            'images' => $images
        ]);
    }

    public function findHouse($rent, $city, $housename){
        $houserepo = $this->getDoctrine()->getRepository(House::class);
        $cityrepo = $this->getDoctrine()->getRepository(City::class);
        $cityId = $cityrepo->findOneBy(array("name"=>$city))->getId();
        $house = $houserepo->findOneBy(array("rent"=>$rent, "city"=>$cityId, "slug"=>$housename));
        return $house;
    }
}

templates/house/carousel.html.twig
{% block carousel_widget %}
    <div class="container super-container-carousel fadein" style="margin-top: 15vh">
        <div class="row container-carousel" style="height: 100%;">
            <div class="col-lg-2 col-md-0 d-block position-relative container-carousel-controller">
                <a class="carousel-control-prev control-carousel position-absolute d-flex" href="#myCarousel" role="button" data-slide="prev"
                   style="right: 100px; bottom: 100px; top: auto!important; left: auto!important;height: 50px; width: 50px; background: #ccc">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                </a>
                <a class="carousel-control-next control-carousel position-absolute d-flex" href="#myCarousel" role="button" data-slide="next"
                   style="right: 50px; bottom: 100px; top: auto!important; left: auto!important;height: 50px; width: 50px; background: #ccc">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                </a>
                <div class="position-absolute bg-green text-white bodoni" style="font-size: 35px; z-index:2; bottom: -20px; right: -50px; height: 120px; width: 200px; text-align: center">
                    {#<span>{{ "1 / " ~ images|length }}</span>#}
                    <span id="actual-slide" class="position-absolute" style="top: 10px; left: 60px">1</span>
                    <span class="position-absolute" style="top: 33px; left: 0; width:100%;text-align: center">/</span>
                    <span class="position-absolute" style="bottom: 10px; right: 60px">{{ images | length + 1}}</span>
                </div>
            </div>
            <div class="col-lg-8 col-md-12 bg-gray" style="padding: 0;">
                <div id="myCarousel" class="carousel slide h-100" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner h-100">
                        <div class="carousel-item active h-100">
                            <img class="d-block w-100 h-100" src="{{ asset('img/houses/' ~ house.mainImage) }}" alt="First slide">
                        </div>
                        {% for image in images %}
                            <div class="carousel-item h-100">
                                <img class="d-block w-100 h-100" src="{{ asset('img/house-images/' ~ image.house.id ~ '/' ~ image.name) }}" alt="First slide">
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="col-lg-2 col-md-0"></div>
        </div>
    </div>

    <script>
        $('#myCarousel').on('slide.bs.carousel', function (event) {
            var slide = parseFloat($("#actual-slide").html());
            var maxSize = $(".carousel-item").length;
            if(event.direction === "left"){
                if(slide === maxSize){
                    slide = 0;
                }
                slide += 1;
                $("#actual-slide").html(slide);
            }else{
                if(slide === 1){
                    slide = maxSize + 1;
                }
                slide -= 1;
                $("#actual-slide").html(slide);
            }
        })
    </script>
{% endblock %}

templates/house/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ house.name ~ " - " ~ house.city.name}}{% endblock %}

{% block additionalStylesheets%}
    <link rel="stylesheet" href="{{ asset('css/house.css') }}">
{% endblock %}

{% block body %}
    <div style="background: #eee">
        <div style="background: #fefefe">
            <div class="container" style=" border-left: 1px solid #ddd; border-right: 1px solid #ddd;">
                    <a class="montserrat fadein text-green letter-space1 pt-5 d-block go-back" href="javascript:history.back()">
                        {{ "Regressar" | upper }}
                    </a>
                    <span class="p-5 montserrat text-gray letter-space2 d-block fadein" style="font-size: 10px; text-align: center; width: 100%">{{ type|upper }}</span>
                    <span class="bodoni text-green fadein d-block" style="font-size: 60px; text-align: center; width: 100%">{{ house.name}}</span>
                    <div class="row pt-5 fadein container-year-share">
                        <div class="col-sm-6 col-lg-4 offset-lg-2 d-flex flex-column year">
                            <span class="text-gray montserrat d-block letter-space1" style="text-align: center; font-size: 12px">{{ "Ano"|upper }}</span>
                            <span class="text-green p-3 bodoni d-block letter-space1" style="text-align: center; font-size: 22px">{{ house.remodelationYear|date('Y')}}</span>
                        </div>
                        <div class="col-sm-6 col-lg-4">
                            <span class="text-gray montserrat d-block letter-space1" style="text-align: center; font-size: 12px">{{ "Partilhar"|upper }}</span>
                            <div class="row container-share">
                                <div class="col-sm-4 share-button p-0">
                                    <i class="fab fa-facebook text-green"></i>
                                </div>
                                <div class="col-sm-4 share-button p-0">
                                    <i class="fab fa-twitter-square text-green"></i>
                                </div>
                                <div class="col-sm-4 share-button p-0">
                                    <i class="fab fa-pinterest-square text-green"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                {% block carousel_widget %}
                    {{ include('house/carousel.html.twig', {'images':images, 'house':house}) }}
                {% endblock %}
                <div class="container-house-description row fadein" style="padding-top: 75px">
                    <div class="col-sm-6 col-lg-4 offset-lg-2">
                        <span class="text-green montserrat" style="font-size: 20px">{{ house.mainDescription }}</span>
                    </div>
                    <div class="col-sm-6 col-lg-4">
                        <span class="montserrat fw-300" style="color: #222;">{{ house.secondaryDescription }}</span>
                    </div>
                </div>
                <div class="row container-map">
                    <div class="house-info">
                        <p class="info-tag montserrat text-green fadein">01</p>
                        <p class="bodoni house-location-tag fadein">Localização</p>
                        <p class="montserrat house-location fw-300 fadein">{{ house.street }}</p>
                        <div class="map fadein">
                            <iframe src="{{ house.location }}" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>                </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="container-helper">
            <div class="container" style="border-left: 1px solid white; border-right: 1px solid white">
                <div class="row" style="margin: 0; width: 100%">
                    <div class="house-info">
                        <p class="info-tag montserrat text-green fadein">02</p>
                        <p class="bodoni house-location-tag fadein" style="border-bottom: 1px solid white;">Amenidades</p>
                        <div class="container mt-5">
                            <div class="row fadein">
                                <div class="col-sm-4 offset-sm-2">
                                    <i class="fas fa-calendar-alt text-green" style="text-align: center; width: 100%; margin: 20px 0; font-size: 50px"></i>
                                    <p class="montserrat letter-space1">Contrução do Prédio</p>
                                    <p class="montserrat text-green fw-300 letter-space1" style="font-size: 25px">{{ house.constructionYear | date("Y")}}</p>
                                </div>
                                <div class="col-sm-4">
                                    <i class="fas fa-square text-green" style="text-align: center; width: 100%; margin: 20px 0; font-size: 50px"></i>
                                    <p class="montserrat letter-space1">Área Bruta</p>
                                    <p class="montserrat text-green fw-300 letter-space1" style="font-size: 25px">{{ house.grossarea ~ 'm'}}<sup>2</sup></p>
                                </div>
                            </div>
                            <div class="row fadein">
                                <div class="col-sm-4 offset-sm-2">
                                    <i class="fas fa-crop text-green" style="text-align: center; width: 100%; margin: 20px 0; font-size: 50px"></i>
                                    <p class="montserrat letter-space1">Área Útil</p>
                                    <p class="montserrat text-green fw-300 letter-space1" style="font-size: 25px">{{ house.netarea ~ 'm'}}<sup>2</sup></p>
                                </div>
                                <div class="col-sm-4 d-flex flex-column">
                                    <i class="fas fa-bed text-green" style="text-align: center; width: 100%; margin: 20px 0; font-size: 50px"></i>
                                    <p class="montserrat letter-space1">Assoalhadas</p>
                                    <p class="montserrat text-green fw-300 letter-space1" style="font-size: 25px">{{ house.rooms}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {{ include('index/contact_widget.html.twig') }}
    </div>

{% endblock %}